### PR TITLE
Add Clinical Lycanthropy

### PR DESCRIPTION
**Pull request by HariMahi**

### CODE REVIEW

**Comment by icyflame** [comment]
Hey @HariMahi , I have already reviewed an earlier PR with this request.

> Succinct paragraph about the entry. (wrapped at 80 columns)

- Please read contributor guidelines. Paragraphs have to be wrapped at 80 columns.
- After making the changes, _do not_ open a new pull request. You should push to the same branch and wait for a review on the same pull request. Opening a new pull request is very disruptive and completely unnecessary.
- One of your entries has a webmd reference. Please don't use webmd as a reference. So, remove them from any other entries you may have put it in


I am closing #55, #56, #57, #58 for now. Once you have made the above mentioned changes, please re-open them one-by-one. This is a soft warning, this kind of spam-y behaviour is **not** appreciated.

**Comment by HariMahi** [comment]
what is meant by 80 columns

**Comment by icyflame** [comment]
https://blog.siddharthkannan.in/editors/programming/2017/12/07/wrapping-text/

You can search online on how to wrap text at 80 columns for your editor.

**Comment by HariMahi** [comment]
I have wrapped the paragraphs, where to add them because you have said that new PR should be avoided

**Comment by icyflame** [comment]
Clone and push from CLI

**Comment by HariMahi** [comment]
how to do it in github directly

**Comment by HariMahi** [comment]
sorry @icyflame I have made a new PR on Clinical Lycanthropy

**Comment by HariMahi** [comment]
Now I have updated patch:5 the old PR patch and have closed the new PR.
Please review it.

**Pull request closed without merging**
