### PR TITLE
Add Placebo Effect

### PR DESCRIPTION
**Pull request by HariMahi**

### CODE REVIEW

**Comment by rudr4x5h** [comment]
@HariMahi try working on something else, as #17 is already under progress.

**Comment by icyflame** [comment]
Hey @d3vil0p3r, 17 is an issue and not a pull request. @HariMahi is free to work on this as no one else is working on it at present.

P.S. Please stop posting maintainer-ish comments on this project, that isn't appreciated. :slightly_smiling_face:

**Comment by HariMahi** [comment]
Please review Placebo Effect

**Comment by icyflame** [comment]
Hey @HariMahi , your pull request was really good! :+1: I removed the webmd and harvard ref and added an article about the effect. I have fixed the paragraph a bit.

Remember that you must wrap the paragraph at 70 characters, in all later contributions if any.

Your changes have been merged into master! Thanks for your work! :smile:

**Comment by HariMahi** [comment]
Thank you
Suggests me some effects and syndromes to add.

**Comment by rudr4x5h** [comment]
@icyflame sure thing. Will take care 😊

**Comment by HariMahi** [comment]
Please commit the PR, I can't see it in Statistics

**Pull request closed without merging**
